GET http://localhost:5000/api/user
Authorization: dGFncHRyb2xsMTp0aG9tYXMxOTk2

###

POST http://localhost:5000/api/user/new
Content-Type: application/json

{
    "username": "bobman1",
    "email": "bob@hotmail.org",
    "password": "bob123" 
}

###

DELETE http://localhost:5000/api/user
Authorization: dGFncHRyb2xsMTp0aG9tYXMxOTk2
